// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal.proto

It has these top-level messages:
	Customer
	Address
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Customer struct {
	Fname string `protobuf:"bytes,1,opt,name=Fname" json:"Fname,omitempty"`
	Lname string `protobuf:"bytes,2,opt,name=Lname" json:"Lname,omitempty"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Customer) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *Customer) GetLname() string {
	if m != nil {
		return m.Lname
	}
	return ""
}

type Address struct {
	Address string `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=City" json:"City,omitempty"`
	State   string `protobuf:"bytes,3,opt,name=State" json:"State,omitempty"`
	Zip     string `protobuf:"bytes,4,opt,name=Zip" json:"Zip,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func init() {
	proto.RegisterType((*Customer)(nil), "internal.Customer")
	proto.RegisterType((*Address)(nil), "internal.Address")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xcc,
	0xb8, 0x38, 0x9c, 0x4b, 0x8b, 0x4b, 0xf2, 0x73, 0x53, 0x8b, 0x84, 0x44, 0xb8, 0x58, 0xdd, 0xf2,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x90, 0xa8, 0x0f, 0x58,
	0x94, 0x09, 0x22, 0x0a, 0xe6, 0x28, 0xc5, 0x73, 0xb1, 0x3b, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17,
	0x0b, 0x49, 0xc0, 0x99, 0x50, 0x8d, 0x70, 0x19, 0x21, 0x2e, 0x16, 0xe7, 0xcc, 0x92, 0x4a, 0xa8,
	0x4e, 0x30, 0x1b, 0x64, 0x5c, 0x70, 0x49, 0x62, 0x49, 0xaa, 0x04, 0x33, 0xc4, 0x38, 0x30, 0x47,
	0x48, 0x80, 0x8b, 0x39, 0x2a, 0xb3, 0x40, 0x82, 0x05, 0x2c, 0x06, 0x62, 0x26, 0xb1, 0x81, 0x5d,
	0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xbc, 0xd5, 0x48, 0xbb, 0x00, 0x00, 0x00,
}
